# Generated by Django 6.0.4 on 2026-04-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='ledger_class',
            field=models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('ENVELOPE', 'Envelope/Pocket')], max_length=50),
        ),
    ]
