# Generated by Django 6.0.4 on 2026-04-20 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0002_initial'),
        ('transactions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EMIPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_months', models.PositiveIntegerField()),
                ('months_paid', models.PositiveIntegerField(default=0)),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deduct_from_ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emi_deductions', to='ledgers.ledger')),
                ('liability_ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emi_plans', to='ledgers.ledger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emi_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
